Add Privilege (PRVG) token
MetaMask/contract-metadata pull request #1048
Opened 2022-05-18 07:09 UTC by kthomas

Add PRVG token

Official Etherscan: https://etherscan.io/token/0x2Ec3275f7aCe4044e499823F511cd58250be8E3d

2022-05-19 07:13 UTC, MRabenda commented on contract-map.json
> +    "logo": "prvg.png",
SVG is required

2022-05-19 07:43 UTC, kthomas commented on contract-map.json
> +    "logo": "prvg.png",
ty 🙏🏻

2022-05-19 08:58 UTC, Newman1515 approved these changes
Ok

2022-05-19 09:03 UTC, Newman1515 requested changes
Nice

2022-06-08 03:25 UTC, kthomas commented
What the actual fuck @MRabenda ???

Can you please merge this?

2022-06-22 13:31 UTC, MRabenda commented
@kthomas - this SVG https://github.com/MetaMask/contract-metadata/blob/34a584f1d1ecf6b2356e9e66861ee99d1f9aeed0/images/prvg.svg has over 300kB - regular one should be ~ 10kB are you able to decrease the size?

2022-06-22 18:49 UTC, kthomas commented
> @kthomas - this SVG https://github.com/MetaMask/contract-metadata/blob/34a584f1d1ecf6b2356e9e66861ee99d1f9aeed0/images/prvg.svg has over 300kB - regular one should be ~ 10kB are you able to decrease the size?

@MRabenda  🤦🏻‍♂️  trust but verify eh? :)

It seems to have been able to be reduced down to 15k. Not sure why that was such a pita but seems within reason now.

Thanks 🍻

2022-06-22 19:18 UTC, kthomas commented
@MRabenda -- they got it down to 8k 🙏🏻 

I guess that SVG is just ridiculous 🤷🏻

2022-06-23 07:13 UTC, MRabenda approved these changes

2022-06-23 07:13 UTC, merged

2022-06-23 07:13 UTC, MRabenda commented
Thanks for your contribution!