Add GGC token
MetaMask/contract-metadata pull request #334
Opened 2019-07-03 10:08 UTC by pawelsome

2019-07-18 11:36 UTC, pawelsome commented
Can somebody review and merge?

2019-08-29 17:05 UTC, estebanmino requested changes
Hi @pawelsome, due to the community activity of this token (less than 200) on the network I'd recommend you to use the watchAsset feature. We are currently minimizing our usage of this token list. Please review our developer docs for our current best practices for displaying your token. You can find watchAsset feature [here](https://metamask.github.io/metamask-docs/Best_Practices/Registering_Your_Token). 
Also, we'd need NEUTRAL reputation on etherscan, is currently UNKNOWN.
Let me know if you have any doubt. Thanks.

2019-10-30 09:31 UTC, pawelsome commented
@estebanmino  would you like to consider adding our GGC token again?
We have more than 200 activity and its growing,
Our etherscan reputation is NEUTRAL now.


In addition to that our token will be available at bitbay.net soon
https://www.bitcoin-squad.com/cryptocurrency-ggc-global-game-coin-available-on-the-bitbay-exchange/  
https://www.facebook.com/BitBayPolska/photos/a.224030321137045/1226090444264356/?type=3&theater 

2020-04-14 11:17 UTC, pawelsome commented
Hi, any update on our Pull request?

Please resolve these labels:
"pending website":
 https://ggc.gg.international/

"pending reputation":
our reputation is NEUTRAL https://etherscan.io/token/0x7F969C4D388Ca0AE39A4FdDB1A6f89878CA2fBf8

"pending community activity":
we have 1,600+ transactions (14.04.2020)
https://etherscan.io/token/0x7F969C4D388Ca0AE39A4FdDB1A6f89878CA2fBf8

2026-08-23 19:06 UTC, closed without merging