ADD VSP Token / Logo (Vesper.Finance)
MetaMask/contract-metadata pull request #804
Opened 2021-04-07 00:09 UTC by michaelmcquaid

Token Address : 0x1b40183efb4dd766f11bda7a7c3ad8982e998421
Token Name: Vesper
Token Decimals: 18
Token Symbol: VSP

Official Website: https://vesper.finance/

Etherscan: https://etherscan.io/address/0x1b40183efb4dd766f11bda7a7c3ad8982e998421
Twitter:  https://twitter.com/VesperFi
Telegram:  https://t.me/joinchat/TbXyYBc94ccAgpIV
Discord:  https://discord.gg/BdctCmDk

Thank you!

2021-04-07 07:14 UTC, xrn approved these changes

2021-04-07 07:14 UTC, xrn requested changes
Can you please remove png file from this PR?

2021-04-08 01:00 UTC, michaelmcquaid commented
Done!

2021-04-08 07:08 UTC, xrn approved these changes

2021-04-08 07:08 UTC, merged